export const regions = [
  'Antofagasta',
  'Araucanía',
  'Arica y Parinacota',
  'Atacama',
  'Aisén',
  'Biobío',
  'Coquimbo',
  'Los Lagos',
  'Magallanes y la Antarctica Chilena',
  'Maule',
  'O’Higgins',
  'Los Ríos Santiago',
  'Tarapacá',
  'Valparaíso'
];

export const towns = [
  'Antofagasta',
  'Calama',
  'Tocopilla',
  'Angol',
  'Temuco',
  'Arica',
  'Copiapó',
  'El Salvador',
  'Coihaique',
  'Puerto Aisén',
  'Chillán',
  'Concepción',
  'Coronel',
  'Lebu',
  'Los Angeles',
  'Lota',
  'Talcahuano',
  'Coquimbo',
  'La Serena',
  'Ancud',
  'Castro',
  'Osorno',
  'Puerto Montt',
  'Valdivia',
  'Punta Arenas',
  'Curicó',
  'Linares',
  'Talca',
  'Rancagua',
  'Iquique',
  'Hanga Roa',
  'San Felipe',
  'Valparaíso',
  'Viña del Mar'
]
